### ISSUE TITLE
Diseño home

### ISSUE THREAD

**Issue by avdata99** [ModernizacionMuniCBA/feria-del-libro#1]
La home page incluirá una lista de los próximos eventos a realizarse.
En la lista podrán usarse las propiedades de cada actividad listada para graficar 
Cada evento: 
 - forma parte de un _espacio_ (es un agrupador de actividades) que podrá tener alguna imagen relacionada.
 - Tiene un titulo
 - Tiene un tipo: Musica en vivo, charla, debate, taller, etc (al que le podremos asignar un ícono o similar)
 - Tiene una descripción (que node debe verse en la lista)
 - Tiene un lugar (que será solo texto, no hay mapa por ahora)

Este diseño y todos los demás deberá recibir validación de Luis y Marisa antes de terminarse

**Comment by avdata99** [comment]
Silvana, me pidieron algunos cambios.
El header esta bien pero tenemos que simplicarlo más a los colores del siguiente diseño. Blanco, verde y quizas ese celeste.

![flyer-feria](https://cloud.githubusercontent.com/assets/3237309/18297770/b8d7f552-7489-11e6-8873-9c63d497ee9d.jpg)

Cuando desplegas el menú izquierdo se ve más cómo se espera que sea.
![image](https://cloud.githubusercontent.com/assets/3237309/18297813/08904680-748a-11e6-96b8-a3269fa03d92.png)

Ese encabezado lateral o similar debe ser el principal o algo similar a eso con los colores del flyer.

**Comment by silvanaroche** [comment]
https://redmine.apps.cordoba.gov.ar/documents/25
